name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: windows-latest
    steps:
      - name: Unity - Test runner
        # You may pin to the exact commit or the version.
        # uses: game-ci/unity-test-runner@be0f55d3cf3dc7289e580d5f8b20a5b49d2a2d3b
        uses: game-ci/unity-test-runner@v2.1.1
